src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=Usager::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usager;

    /**
     * @ORM\OneToMany(targetEntity=LigneCommande::class, mappedBy="id_commande", orphanRemoval=true)
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUsager(): Usager
    {
        return $this->usager;
    }

    public function setUsager(?Usager $usager): self
    {
        $this->usager = $usager;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }
}

templates/pages/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usager index{% endblock %}

{% block body %}


    <div class="card col-md-12">
        <div class="card-header text-center">
            <h1>Espace administrateur</h1>
        </div>
        <div class="card-body row justify-content-center">
            <div class="col-md-3">
                <div class="card">
                    <img src="{{ asset('images/pizza.jpg') }}">
                    <div class="card-body">
                        <h5 class="card-title">Gérer les articles</h5>
                        <a href="{{ path('article_index') }}" class="btn btn-primary">Ouvrir</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img src="{{ asset('images/junk_food.jpg') }}">
                    <div class="card-body">
                        <h5 class="card-title">Gérer les catégories</h5>
                        <a href="{{ path('categorie_index') }}" class="btn btn-primary">Ouvrir</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img src="{{ asset('images/commande.png') }}">
                    <div class="card-body">
                        <h5 class="card-title">Gérer les commandes</h5>
                        <a href="{{ path('commande_index') }}" class="btn btn-primary">Ouvrir</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/boutique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}
	<div class="card col-md-12">
		<div class="card-header text-center">
			<h1>Catégories</h1>
		</div>
		<div class="card-body row justify-content-center">
			{% for categorie in categories %}
			<div class="col-md-3">
				<div class="card">
					<img src="{{ asset(categorie.visuel) }}" class="card-img-top text-center" style="width:100%" alt="Logo Boutique Symfony">
					<div class="card-body">
						<h5 class="card-title">{{ categorie.libelle }}</h5>
						<p class="card-text">{{ categorie.texte }}</p>
						<a href="{{ path("rayon", { 'id': categorie.id}) }}" class="btn btn-primary">accéder au rayon</a>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	</div>
{% endblock %}

templates/pages/chercher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}

	<div class="card col-md-12">
		<div class="card-header text-center">
			{%  if articles|length > 0 %}
			<h1>{{ recherche }} : {{ articles|length }} Produit(s)</h1>
		</div>
		<div class="card-body row justify-content-center">
			{% for article in articles %}
				<div class="col-md-3">
					<div class="card">
						<img src="{{ asset(article.visuel) }}" class="card-img-top text-center" style="width:100%" alt="Logo Boutique Symfony">
						<div class="card-body">
							<h5 class="card-title">{{ article.libelle }}</h5>
							<p class="card-text">{{ article.texte }}</p>
							<a href="{{ path("panier_ajouter", { 'idArticle': article.id, 'quantite' : 1}) }}" class="btn btn-primary">ajouter ce article au panier</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		{% else %}
			<h1>Aucun résultat</h1>
		</div>
		{%  endif %}
	</div>
{% endblock %}

templates/pages/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}
    <div class="example-wrapper text-center">
        <h1>Votre commande</h1>
            <div class="column justify-content-center">
                <h2>Commande N°{{ commande.id }}</h2>
                <h2>Créée le {{ commande.dateCommande|date('Y-m-d') }}</h2>
                <h2>Statut : {{ commande.statut }}</h2>
            </div>
            <a href="{{ path('boutique') }}" class="btn btn-danger">Retourner à la boutique</a>
        <ul></ul>
    </div>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salut gente demoiseaux{% endblock %}

{% block body %}

    <div class="row justify-content-center">
        <div class="card col-md-4 text-center">
            <div class="card-header text-center">
                <h1>{{ 'default.contact.page' | trans}}</h1>
            </div>
            <div class="card-body">
                <div class="card text-center">
                    <div class="card-body">
                    <img src="{{ asset("images/iut2_info.png") }}" class="card-img-top text-center" style="width:100%" alt="Logo iut2 Grenoble">
                        <p class="card-text">{{ 'default.contact.sousTitre' | trans}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}
    <div class="card col-md-12">
        <div class="card-header text-center">
            <h1>{{ 'default.index.titre' | trans}}</h1>
        </div>
        <a href="{{ path("boutique") }}">
            <div class="card-body clickable">
                <div class="card text-center">
                    <img src="{{ asset("images/epicerie.jpg") }}" class="card-img-top text-center" style="width:100%" alt="Logo Boutique Symfony">
                    <div class="card-body">
                        <p class="card-text">{{ 'default.index.sousTitre' | trans}}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>

{% endblock %}

templates/pages/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}
	<div class="card col-md-12">
	{%  if articles|length > 0  %}
		<div class="card-header text-center">
			<h1>Panier : {{ total }}€</h1>
		</div>
		<div class="card-body row text-center justify-content-center">
			{% for article in articles %}
				<div class="col-md-3">
					<div class="card">
						<img src="{{ asset(article.visuel) }}" class="card-img-top text-center" style="width:100%" alt="Logo Boutique Symfony">
						<div class="card-body">
							<h5 class="card-title">{{ article.libelle }}</h5>
							<p class="card-text">{{ article.prix | currency_convert | format_currency(devise) }}</p>
							<div class="row justify-content-center mx-auto" style="margin-bottom:10px;">
								<a href="{{ path('panier_enlever', {'idArticle' : article.id, 'quantite' : 1}) }}" class="btn btn-secondary">-</a>
								<p class="card-text" style="margin: 10px; font-weight: bold;">{{ article.quantite }}</p>
								<a href="{{ path('panier_ajouter', { 'idArticle': article.id, 'quantite' : 1}) }}" class="btn btn-secondary">+</a>
							</div>
							<a href="{{ path('panier_supprimer', { 'idArticle': article.id}) }}" class="btn btn-danger" style="height: 40px">Supprimer</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<a href="{{ path('panier_vider') }}" class="btn btn-danger">Vider le panier</a>
		<br>
		<a href="{{ path('creer_commande') }}" class="btn btn-primary">Créer commande</a>
	</div>
	{% else %}
		<div class="card-header text-center">
			<h1>Votre panier est vide</h1>
		</div>
		<a href="{{ path('boutique') }}" class="btn btn-primary">Aller à la boutique</a>
	</div>
	{% endif %}
{% endblock %}

templates/pages/rayon.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}
	<div class="card col-md-12">
		<div class="card-header text-center">
			<h1>Articles</h1>
		</div>
		<div class="card-body row justify-content-center">
			{% for article in articles %}
				<div class="col-md-3">
					<div class="card">
						<img src="{{ asset(article.visuel) }}" class="card-img-top text-center" style="width:100%" alt="Logo Boutique Symfony">
						<div class="card-body text-center">
							<h5 class="card-title">{{ article.libelle }}</h5>
							<p class="card-text">{{ article.texte }}</p>
							<p class="card-text">{{ article.prix | currency_convert |format_currency(devise) }}</p>
							<a href="{{ path("panier_ajouter", { 'idArticle': article.id, 'quantite' : 1}) }}" class="btn btn-primary">ajouter ce article au panier</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}